# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4126f477bd415f39735bbc98d6b1cb4e09adf5c31d1ee6aa4af7ddcb9fff61e1d1e200c08848924462814c1492ed72368e277927ee1ffa43ab5a1c4de191167c

test:
  secret_key_base: 8fafc162ad81a0e657b5836ff89936b5853426c6b2485196c3def1ae47890eac6e106190f805bb869043693063bd54e10b6896e7cbf7caba9eca816a5500b7f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
